#VeeamReport config file
TelegramBotToken=35463456354:ASDFgh4378tgyhdash56w4rvUoWI
TelegramChatId=-10014234324324
#CustomRPOMap=[{"JobName":"Custom Backup","RPOMap":{"168":"Green","336":"Yellow"}},{"JobName":"Custom 2 Backup","RPOMap":{"9998":"Green","9999":"Yellow"}}]
#IncludeBackupsWithoutJob=true